# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Groute' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Groute
  pod 'Firebase/Analytics'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'GoogleSignIn'
  pod 'Kingfisher' 
  
  target 'GrouteTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GrouteUITests' do
    # Pods for testing
  end

end
